title: Min Docker Jekyll Site
description: Testsite i Docker
baseurl: ""
url: ""
webmaster: "Daniel Thörnsjö"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
